[package]
name = "uu_diff"
description = "diffutils ~ implementation of the diff utility"
categories.workspace = true
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
diffutils_core = { workspace = true }
same-file = { workspace = true }
diff = { workspace = true }
unicode-width = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
regex = { workspace = true }
diffutils_core = { workspace = true, features = ["test-utils"] }

[lib]
path = "./src/diff.rs"
